theme: jekyll-theme-cayman
title: JACDAC
description: "Joint Asynchronous Communications; Device Agnostic Control. <br/>Authors: J. Devine, M. Moskal, P. Halleux, T. Ball, S. Hodges, J. Finney."
logo: /images/logo.png