theme: jekyll-theme-cayman
title: JACDAC
description: "JACDAC (Joint Asynchronous Communications; Device Agnostic Control) is a single wire protocol for the plug and play of sensors, actuators, and microcontrollers (MCUs) for use within the contexts of rapid prototyping, making, and computer science education."
github:
  repository_url: https://github.com/jacdac/jacdac